DROP TABLE IF EXISTS Person;

CREATE TABLE IF NOT EXISTS Person (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	username varchar(100) NOT NULL, 
	year_of_birth int NOT NULL, 
	password varchar NOT NULL
);
